version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker
      - dockerd > /var/log/dockerd.log 2>&1 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "Installing AWS CLI and jq"
      - yum install -y jq
      - echo "Fetching GitHub Personal Access Token from Secrets Manager"
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id github/personal_access_token --query SecretString --output text | jq -r .GITHUB_TOKEN)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 975050245649.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=975050245649.dkr.ecr.ap-south-1.amazonaws.com/lambda-container-repo-github/test
      - echo Authenticating with GitHub using Personal Access Token...
      - git clone https://$GITHUB_TOKEN@github.com/Syedboo/Stock_prediction.git
      - echo Changing to lambda_container directory...
      - cd Stock_prediction/lambda_container

  build:
    commands:
      - echo Starting build...
      - echo "Printing the source repository URL:"
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo "Printing all CodeBuild environment variables:"
      - env  # This will print all environment variables including the source information
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t lambda-container .
      - docker tag lambda-container:latest $REPOSITORY_URI:latest



  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest



artifacts:
  files:
    - /tmp/dummy_artifact.txt
