version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 975050245649.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=975050245649.dkr.ecr.ap-south-1.amazonaws.com/lambda-container-repo
      - cd lambda_container

  build:
    commands:
      - echo Build started on `date`
      - docker build -t lambda-container .
      - docker tag lambda-container:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest

artifacts:
  files: null
